# Generated by Django 2.1.4 on 2018-12-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
