# Generated by Django 2.1.4 on 2018-12-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0002_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
