# Generated by Django 2.1.4 on 2018-12-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0003_auto_20181209_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phoneno',
            field=models.IntegerField(blank=True),
        ),
    ]
